package com.redhat.ponto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitacao implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Solicitacao() {
    }

}