package com.redhat.pagamento;

/**
 * This class was automatically generated by the data modeler tool.
 */

package br.com.rotadasbandeiras.pagamentos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitacao implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nomeDoSolicitante;
   private java.lang.String emailDoSolicitante;
   private java.lang.String identificacaoDoPagamento;
   private java.util.Date dataDoPagamentoAntecipada;
   private java.lang.String emailInteressados;

   private java.lang.Boolean aprovacaoDoGerente;

   private java.lang.Boolean aprovacaoDoDiretor;

   private java.lang.Boolean aprovacaoDoPresidente;

   private java.lang.String listaDeEmailFinal;

   private java.lang.Boolean usuarioDiferenciado;

   public Solicitacao()
   {
   }

   public java.lang.String getNomeDoSolicitante()
   {
      return this.nomeDoSolicitante;
   }

   public void setNomeDoSolicitante(java.lang.String nomeDoSolicitante)
   {
      this.nomeDoSolicitante = nomeDoSolicitante;
   }

   public java.lang.String getEmailDoSolicitante()
   {
      return this.emailDoSolicitante;
   }

   public void setEmailDoSolicitante(java.lang.String emailDoSolicitante)
   {
      this.emailDoSolicitante = emailDoSolicitante;
   }

   public java.lang.String getIdentificacaoDoPagamento()
   {
      return this.identificacaoDoPagamento;
   }

   public void setIdentificacaoDoPagamento(
         java.lang.String identificacaoDoPagamento)
   {
      this.identificacaoDoPagamento = identificacaoDoPagamento;
   }

   public java.util.Date getDataDoPagamentoAntecipada()
   {
      return this.dataDoPagamentoAntecipada;
   }

   public void setDataDoPagamentoAntecipada(
         java.util.Date dataDoPagamentoAntecipada)
   {
      this.dataDoPagamentoAntecipada = dataDoPagamentoAntecipada;
   }

   public String toString()
   {
      return "SOLICITACAO: [\n" +
            "    Nome do solicitante: " + nomeDoSolicitante + "\n" +
            "    Email do solicitante: " + emailDoSolicitante + "\n" +
            "    Identificacao do pagamento: " + identificacaoDoPagamento + "\n" +
            "    Data do pagamento antecipada: " + dataDoPagamentoAntecipada + "\n" +
            "    Emails dos interessados: " + emailInteressados + "\n" +
            "    Aprovacao do Gerente: " + aprovacaoDoGerente + "\n" +
            "    Aprovacao do Diretor: " + aprovacaoDoDiretor + "\n" +
            "    Aprovacao do Presidente: " + aprovacaoDoPresidente + "\n" +
            "    Usuario diferenciado: " + usuarioDiferenciado + "\n" +
            "    Lista de emails final: " + listaDeEmailFinal + "\n" +
            "]";
   }

   public java.lang.String getEmailInteressados()
   {
      return this.emailInteressados;
   }

   public void setEmailInteressados(java.lang.String emailInteressados)
   {
      this.emailInteressados = emailInteressados;
   }

   public java.lang.Boolean getAprovacaoDoGerente()
   {
      return this.aprovacaoDoGerente;
   }

   public void setAprovacaoDoGerente(java.lang.Boolean aprovacaoDoGerente)
   {
      this.aprovacaoDoGerente = aprovacaoDoGerente;
   }

   public java.lang.Boolean getAprovacaoDoDiretor()
   {
      return this.aprovacaoDoDiretor;
   }

   public void setAprovacaoDoDiretor(java.lang.Boolean aprovacaoDoDiretor)
   {
      this.aprovacaoDoDiretor = aprovacaoDoDiretor;
   }

   public java.lang.Boolean getAprovacaoDoPresidente()
   {
      return this.aprovacaoDoPresidente;
   }

   public void setAprovacaoDoPresidente(java.lang.Boolean aprovacaoDoPresidente)
   {
      this.aprovacaoDoPresidente = aprovacaoDoPresidente;
   }

   public java.lang.String getListaDeEmailFinal()
   {
      return this.listaDeEmailFinal;
   }

   public void setListaDeEmailFinal(java.lang.String listaDeEmailFinal)
   {
      this.listaDeEmailFinal = listaDeEmailFinal;
   }

   public java.lang.Boolean getUsuarioDiferenciado()
   {
      return this.usuarioDiferenciado;
   }

   public void setUsuarioDiferenciado(java.lang.Boolean usuarioDiferenciado)
   {
      this.usuarioDiferenciado = usuarioDiferenciado;
   }

   public Solicitacao(java.lang.String nomeDoSolicitante,
         java.lang.String emailDoSolicitante,
         java.lang.String identificacaoDoPagamento,
         java.util.Date dataDoPagamentoAntecipada,
         java.lang.String emailInteressados,
         java.lang.Boolean aprovacaoDoGerente,
         java.lang.Boolean aprovacaoDoDiretor,
         java.lang.Boolean aprovacaoDoPresidente,
         java.lang.String listaDeEmailFinal,
         java.lang.Boolean usuarioDiferenciado)
   {
      this.nomeDoSolicitante = nomeDoSolicitante;
      this.emailDoSolicitante = emailDoSolicitante;
      this.identificacaoDoPagamento = identificacaoDoPagamento;
      this.dataDoPagamentoAntecipada = dataDoPagamentoAntecipada;
      this.emailInteressados = emailInteressados;
      this.aprovacaoDoGerente = aprovacaoDoGerente;
      this.aprovacaoDoDiretor = aprovacaoDoDiretor;
      this.aprovacaoDoPresidente = aprovacaoDoPresidente;
      this.listaDeEmailFinal = listaDeEmailFinal;
      this.usuarioDiferenciado = usuarioDiferenciado;
   }

}